"""add qianfan_ocr_fields to settings table

Revision ID: qianfan_ocr_fields
Revises: 38292967f3ca
Create Date: 2025-12-20 15:30:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = "qianfan_ocr_fields"
down_revision = "38292967f3ca"
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    """Check if column exists"""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """
    Add qianfan_api_key and qianfan_api_base columns to settings table.

    Idempotent: checks if columns exist before adding.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists("settings", "qianfan_api_key"):
        op.add_column(
            "settings",
            sa.Column("qianfan_api_key", sa.String(length=500), nullable=True),
        )
    if not _column_exists("settings", "qianfan_api_base"):
        op.add_column(
            "settings",
            sa.Column("qianfan_api_base", sa.String(length=500), nullable=True),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "qianfan_api_key")
    op.drop_column("settings", "qianfan_api_base")
    # ### end Alembic commands ###
